name: Publish Static Web App to Azure Blob Storage

on:
  push:
    branches: [ master ]

jobs:
  login_and_publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v1

    - name: Login to Azure
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Publish app
      uses: Azure/cli@v1.0.0
      with:
        azcliversion: latest
        inlineScript: |
          ls $GITHUB_WORKSPACE
          az storage blob upload-batch -s $GITHUB_WORKSPACE -d \$web --account-name ${{ secrets.STORAGE_ACCOUNT_NAME }} --only-show-errors